/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.FlowLayout;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.NumberFormatter;
import wald.waldgenerator;

/**
 *
 * @author Alexander
 */
public class GenFrame extends javax.swing.JFrame {

    private final int maxSize = 1000;
    private MainFrame mainFrame;
    private File file;
    private int xSize;
    private int ySize;
    private int lastFx;
    private int lastFy;
    private ArrayList<int[]> fires;
    private File generated;
    private final Verifier verifier;
    private final DefaultListModel<String> firesList = new DefaultListModel<>();

    /**
     * Creates new form GenFrame
     */
    public GenFrame() {
        verifier=new Verifier();
        this.ySize = 100;
        this.xSize = 100;
        initComponents();
        tX.setName("tX");
        tFX.setName("tFX");
        tY.setName("tY");
        tFY.setName("tFY");
        tX.setInputVerifier(verifier);
        tFX.setInputVerifier(verifier);
        tY.setInputVerifier(verifier);
        tFY.setInputVerifier(verifier);
        fires = new ArrayList<>();
        generated=null;
    }
    
    public GenFrame(MainFrame main){
          this();
          mainFrame=main;
    }

    private boolean readFileData(File f) {
        WoodChecker check=new WoodChecker(f);
        if(!check.isWood()) return false;
        int x=check.getSize()[0];
        int y=check.getSize()[1];
        int result = JOptionPane.showConfirmDialog(this, "Read the data from file?\nAll current changes will be lost!!!", "Replace contents", JOptionPane.YES_NO_OPTION);
        switch (result) {
            case JOptionPane.YES_OPTION:
                this.fires = check.fires;
                firesList.clear();
                for(int i[]:fires)
                    firesList.addElement(String.format("%d, %d", i[1], i[0]));
                this.xSize = x;
                this.ySize = y;
                tX.setText(x+"");
                tY.setText(x+"");
                generated=f;
                return true;
            case JOptionPane.NO_OPTION:
                return false;
            case JOptionPane.CLOSED_OPTION:
                return false;
            default:
                return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sFires = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        wAdd = new javax.swing.JDialog();
        xFlabel = new javax.swing.JLabel();
        yFlabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tFX = new javax.swing.JFormattedTextField();
        tFY = new javax.swing.JFormattedTextField();
        dNoChanges = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser(){
            @Override
            public void approveSelection(){
                File f = getSelectedFile();
                if(f.exists()&&!readFileData(f)){
                    int result = JOptionPane.showConfirmDialog(this,"Overwrite this file?","File exists!",JOptionPane.YES_NO_OPTION);
                    switch(result){
                        case JOptionPane.YES_OPTION:
                        super.approveSelection();
                        return;
                        case JOptionPane.NO_OPTION:
                        return;
                        case JOptionPane.CLOSED_OPTION:
                        return;
                    }
                }
                super.approveSelection();
            }
        };
        dataReplace = new javax.swing.JOptionPane();
        dialog = new javax.swing.JOptionPane();
        dFireWasSet = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        tFilename = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bGenerate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bAdd = new javax.swing.JButton();
        bRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lFires = new javax.swing.JList(firesList);
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        tX = new javax.swing.JFormattedTextField();
        tY = new javax.swing.JFormattedTextField();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        sFires.setViewportView(jTextArea2);

        wAdd.setTitle("Add new fire");
        wAdd.setResizable(false);

        xFlabel.setText("X:");

        yFlabel.setText("Y:");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tFX.setText("0");
        tFX.setToolTipText(String.format("Valide values: 0-%d",xSize));

        tFY.setText("0");
        tFY.setToolTipText(String.format("Valide values: 0-%d",ySize));

        javax.swing.GroupLayout wAddLayout = new javax.swing.GroupLayout(wAdd.getContentPane());
        wAdd.getContentPane().setLayout(wAddLayout);
        wAddLayout.setHorizontalGroup(
            wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wAddLayout.createSequentialGroup()
                        .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xFlabel)
                            .addComponent(yFlabel))
                        .addGap(18, 18, 18)
                        .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFX)
                            .addComponent(tFY, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                    .addGroup(wAddLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wAddLayout.setVerticalGroup(
            wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xFlabel)
                    .addComponent(tFX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yFlabel)
                    .addComponent(tFY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wAdd.pack();

        dNoChanges.setResizable(false);

        jLabel10.setText("Nothing was created. Continue?");

        jButton10.setText("Yes");

        jButton11.setText("No");

        javax.swing.GroupLayout dNoChangesLayout = new javax.swing.GroupLayout(dNoChanges.getContentPane());
        dNoChanges.getContentPane().setLayout(dNoChangesLayout);
        dNoChangesLayout.setHorizontalGroup(
            dNoChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNoChangesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dNoChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dNoChangesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dNoChangesLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dNoChangesLayout.setVerticalGroup(
            dNoChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNoChangesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dNoChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dNoChanges.pack();

        setTitle("WoodGenerator");

        jLabel1.setText("Filename: ");

        tFilename.setText("browse a file");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bGenerate.setText("Generate");
        bGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateActionPerformed(evt);
            }
        });

        jLabel3.setText("Horizontal: ");

        jLabel4.setText("Fields");

        jLabel5.setText("Vertical: ");

        jLabel6.setText("Fields");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Fire Source(s):");

        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bRemove.setText("Remove");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lFires);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAdd)
                    .addComponent(bRemove)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRemove)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton7.setText("Delete");

        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("OK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        tX.setText("100");
        tX.setToolTipText("Valide values: 1-1000");

        tY.setText("100");
        tY.setToolTipText("Valide values: 1-1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tX)
                                    .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(bGenerate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(tY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGenerate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean addFire(int x, int y) {
        int result;
        for (int i = 0; i < fires.size(); i++) {
            if (fires.get(i)[0] == x && fires.get(i)[1] == y) {
                String[] options = new String[] {"OK", "Give another point"};
                result = JOptionPane.showOptionDialog(null, 
                        String.format("Fire Source exists in (%d, %d)", x, y), 
                        "Fire exists", JOptionPane.DEFAULT_OPTION, 
                        JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                switch (result) {
                    case 0:
                        return true;
                    case 1:
                        return false;
                    case JOptionPane.CLOSED_OPTION:
                        return false;
                    default:
                        return false;
                }
            }
        }
        fires.add(new int[]{x,y});
        firesList.addElement(String.format("%d, %d", Integer.parseInt(tFX.getText()), Integer.parseInt(tFY.getText())));
        result = JOptionPane.showConfirmDialog(this, "Add more Fire Sources?", "More Sources", JOptionPane.YES_NO_OPTION);
        switch (result) {
            case JOptionPane.YES_OPTION:
                return false;
            case JOptionPane.NO_OPTION:
                return true;
            case JOptionPane.CLOSED_OPTION:
                return true;
            default:
                return true;
        }
    }

    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        if(fires.size()<1) return;
        int index=lFires.getSelectedIndex();
        if(index<0) {
            JOptionPane.showMessageDialog(this, "Please select a fire source!", "No selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int result = JOptionPane.showConfirmDialog(this, String.format("Really remove fire (%s) ?",lFires.getSelectedValue()), "Fire remove", JOptionPane.YES_NO_OPTION);
        switch (result) {
            case JOptionPane.YES_OPTION:
                fires.remove(index);
                firesList.remove(index);
            case JOptionPane.NO_OPTION:
            case JOptionPane.CLOSED_OPTION:
        }
    }//GEN-LAST:event_bRemoveActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        tFX.setText(0+"");
        tFY.setText(0+"");
        xFlabel.setText(String.format("X (%d - %d)",0,xSize-1));
        yFlabel.setText(String.format("Y (%d - %d)",0,ySize-1));  
        wAdd.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(addFire(Integer.parseInt(tFX.getText()), Integer.parseInt(tFY.getText()))) wAdd.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        wAdd.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateActionPerformed
        if (file == null) {
            JOptionPane.showMessageDialog(this, "Select the file first!", "No file selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(waldgenerator.create(xSize, ySize, fires, file)){
            JOptionPane.showMessageDialog(this, String.format("File %s was generated", file.getName()), "Done!", JOptionPane.INFORMATION_MESSAGE);
            generated=file;
        } else {
            JOptionPane.showMessageDialog(this, "Problems by accessing the file", "Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bGenerateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (file == null) {
            fileChooser.setCurrentDirectory(new File("src/data/wald"));
        } else {
            fileChooser.setCurrentDirectory(file);
            fileChooser.setSelectedFile(file);
        }
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            tFilename.setText(PathShortener.pathLengthShortener(file.getName(), 27));
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tXActionPerformed(FocusEvent evt) {                                   
        if(tX.getText().equals("")){
            tX.setText(xSize+"");
            return;
        }
        xSize=Integer.parseInt(tFX.getText());
    }
    
    private void tYActionPerformed(FocusEvent evt) {                                   
        if(tY.getText().equals("")){
            tY.setText(ySize+"");
            return;
        }
        ySize=Integer.parseInt(tFY.getText());
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int result;
        if(generated==null) {
            result = JOptionPane.showConfirmDialog(this, "Nothing was generated. Hide generator?", "Nothing generated", JOptionPane.YES_NO_OPTION);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    this.setVisible(false);
            }
        } else {
            result = JOptionPane.showConfirmDialog(this, "Use the latest generated file for input?", "Set input file", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    mainFrame.setIn(generated);
                case JOptionPane.NO_OPTION:
                    this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GenFrame().setVisible(true);
            }
        });
    }
    
    private class Verifier extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            int tmp;
            JTextField text = (JTextField)input;
            String value = text.getText().trim();
            try {
                tmp=Integer.parseInt(value);
                switch(text.getName()){
                    case "tFX": if(tmp<0||tmp>(xSize-1)) throw new NumberFormatException();
                        lastFx=tmp; break;
                    case "tYX": if(tmp<0||tmp>(ySize-1)) throw new NumberFormatException();
                        lastFy=tmp; break;
                    case "tX": if(tmp<1||tmp>maxSize) throw new NumberFormatException();
                        xSize=tmp; break;
                    case "tY": if(tmp<1||tmp>maxSize) throw new NumberFormatException();
                        ySize=tmp;break;
                    default:
                }
            } catch (NumberFormatException e) {
                switch(input.getName()){
                    case "tFX": text.setText(lastFx+""); break;
                    case "tYX": text.setText(lastFy+""); break;
                    case "tX": text.setText(xSize+""); break;
                    case "tY": text.setText(ySize+"");break;
                    default:
                }
               return false;
            }
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bGenerate;
    private javax.swing.JButton bRemove;
    private javax.swing.JOptionPane dFireWasSet;
    private javax.swing.JDialog dNoChanges;
    private javax.swing.JOptionPane dataReplace;
    private javax.swing.JOptionPane dialog;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList lFires;
    private javax.swing.JScrollPane sFires;
    private javax.swing.JFormattedTextField tFX;
    private javax.swing.JFormattedTextField tFY;
    private javax.swing.JLabel tFilename;
    private javax.swing.JFormattedTextField tX;
    private javax.swing.JFormattedTextField tY;
    private javax.swing.JDialog wAdd;
    private javax.swing.JLabel xFlabel;
    private javax.swing.JLabel yFlabel;
    // End of variables declaration//GEN-END:variables

}
