/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import static gui.TheWood.mouseDownCompCoords;
import java.awt.Point;
import java.awt.event.FocusEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.*;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author a.diener
 */
public class MainFrame extends javax.swing.JFrame {

        
    protected File inFile;
    protected File outFile;
    protected int helpers;
    protected int MBSaved;
    protected int mode;
    private GenFrame gen;
    private TheWood view;
    private Verifier verifier;
    private Crashtest test;

    protected void setIn(File file){
        inFile=file;
        tInput.setText(PathShortener.pathLengthShortener(inFile.getName(),27));
    }
    
    private void initFrames(){
        gen=new GenFrame(this);
        view=new TheWood(this);
    }
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        verifier=new Verifier();
        initComponents();
        dAbout.pack();
        tHCount.setName("tHCount");
        tMBSaved.setName("tMBSaved");
        tHCount.setInputVerifier(verifier);
        tMBSaved.setInputVerifier(verifier);
        initFrames();
        helpers=Integer.parseInt(tHCount.getText());
        MBSaved=Integer.parseInt(tMBSaved.getText());
        processing.setResizable(false);
        processing.setUndecorated(true);
        processing.addMouseListener(new MouseListener(){
            public void mouseReleased(MouseEvent e) {
                mouseDownCompCoords = null;
            }
            public void mousePressed(MouseEvent e) {
                mouseDownCompCoords = e.getPoint();
            }
            public void mouseExited(MouseEvent e) {
            }
            public void mouseEntered(MouseEvent e) {
            }
            public void mouseClicked(MouseEvent e) {
            }
        });

        processing.addMouseMotionListener(new MouseMotionListener(){
            public void mouseMoved(MouseEvent e) {
            }

            public void mouseDragged(MouseEvent e) {
                Point currCoords = e.getLocationOnScreen();
                processing.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
            }
        });
        
        bar.setIndeterminate(true);  
        bar.setStringPainted(true);   
        bar.setString("Working..."); 
        stopTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test.stop();
            }
        });
        processing.pack();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        fileChooser = new javax.swing.JFileChooser();
        dReplace = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dAbout = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        processing = new javax.swing.JDialog();
        bar = new javax.swing.JProgressBar();
        status = new javax.swing.JLabel();
        stopTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tInput = new javax.swing.JLabel();
        tOutput = new javax.swing.JLabel();
        bOpenIn = new javax.swing.JButton();
        bGenWood = new javax.swing.JButton();
        bOpenOut = new javax.swing.JButton();
        bShowIn = new javax.swing.JButton();
        bRun = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lMode = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tHCount = new javax.swing.JFormattedTextField();
        tMBSaved = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mViewer = new javax.swing.JMenuItem();
        bTest = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mAbout = new javax.swing.JMenuItem();

        jLabel6.setText("This file exists. Replace?");

        jButton1.setText("Yes");

        jButton2.setText("No, select another one");

        jButton3.setText("Cancel");

        javax.swing.GroupLayout dReplaceLayout = new javax.swing.GroupLayout(dReplace.getContentPane());
        dReplace.getContentPane().setLayout(dReplaceLayout);
        dReplaceLayout.setHorizontalGroup(
            dReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dReplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(dReplaceLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dReplaceLayout.setVerticalGroup(
            dReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dReplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dReplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dAbout.setTitle("About");

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText("WoodBurningSimulator");

        jLabel9.setText("Ver. 1.0.0");

        jLabel10.setText("Owners: ");

        jLabel12.setText("Authors: ");

        jLabel13.setText("Simon von Hall");

        jLabel14.setText("Alexander Diener");

        jLabel15.setText("Core:");

        jLabel16.setText("GUI:");

        jLabel11.setText("Phillip Klinkhammer");

        jLabel17.setText("Florian Krüger ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)))
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(51, 51, 51))))
        );

        javax.swing.GroupLayout dAboutLayout = new javax.swing.GroupLayout(dAbout.getContentPane());
        dAbout.getContentPane().setLayout(dAboutLayout);
        dAboutLayout.setHorizontalGroup(
            dAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(175, 175, 175))
            .addGroup(dAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dAboutLayout.setVerticalGroup(
            dAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        processing.setResizable(false);

        status.setText("...");
        status.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stopTest.setText("Interrupt after current dim");

        javax.swing.GroupLayout processingLayout = new javax.swing.GroupLayout(processing.getContentPane());
        processing.getContentPane().setLayout(processingLayout);
        processingLayout.setHorizontalGroup(
            processingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(processingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stopTest)
                .addGap(40, 40, 40))
        );
        processingLayout.setVerticalGroup(
            processingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WBS");

        jLabel1.setText("Helpercount:");

        jLabel2.setText("Must be saved:");

        tInput.setText("browse/create a file");
        tInput.setName(""); // NOI18N

        tOutput.setText("browse a file");

        bOpenIn.setText("Browse");
        bOpenIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenInActionPerformed(evt);
            }
        });

        bGenWood.setText("Create");
        bGenWood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenWoodActionPerformed(evt);
            }
        });

        bOpenOut.setText("Browse");
        bOpenOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenOutActionPerformed(evt);
            }
        });

        bShowIn.setText("Show");
        bShowIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowInActionPerformed(evt);
            }
        });

        bRun.setText("Run");
        bRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunActionPerformed(evt);
            }
        });

        jLabel3.setText("Mode:");

        lMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emergency", "Preventive" }));

        jLabel4.setText("Input:");

        jLabel5.setText("Output:");

        tHCount.setText("50");
        tHCount.setToolTipText("Valide values: 0-...");

        tMBSaved.setText("50");
        tMBSaved.setToolTipText("Valide values: 0-100");

        jLabel7.setText("%");

        mFile.setText("File");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bGenWood, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), mFile, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        mViewer.setText("Open Viewer");
        mViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mViewerActionPerformed(evt);
            }
        });
        mFile.add(mViewer);

        bTest.setText("Crashtest");
        bTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTestActionPerformed(evt);
            }
        });
        mFile.add(bTest);

        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mFile.add(mExit);

        jMenuBar1.add(mFile);

        mHelp.setText("Help");

        mAbout.setText("About");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        mHelp.add(mAbout);

        jMenuBar1.add(mHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bOpenIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bGenWood)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bShowIn))
                            .addComponent(bOpenOut)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(bRun))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tHCount))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tMBSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tInput)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOpenIn)
                    .addComponent(bGenWood)
                    .addComponent(bShowIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tOutput)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bOpenOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tHCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tMBSaved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bRun)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void refreshView(){
        view=new TheWood(this);        
    }
    
    private void bOpenOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenOutActionPerformed
        if (outFile==null) {
            fileChooser.setCurrentDirectory(new File("data/out"));
        } else {
            fileChooser.setCurrentDirectory(outFile);
            fileChooser.setSelectedFile(outFile);
        }
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            outFile = fileChooser.getSelectedFile();
            tOutput.setText(PathShortener.pathLengthShortener(outFile.getName(),26));
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_bOpenOutActionPerformed

    private void bOpenInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenInActionPerformed
        if (inFile==null) {
            fileChooser.setCurrentDirectory(new File("data/wald"));
        } else {
            fileChooser.setCurrentDirectory(inFile);
            fileChooser.setSelectedFile(inFile);
        }
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            inFile = fileChooser.getSelectedFile();
            tInput.setText(PathShortener.pathLengthShortener(inFile.getName(),27));
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_bOpenInActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_mExitActionPerformed

    private void bGenWoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenWoodActionPerformed
      gen.setVisible(true);
    }//GEN-LAST:event_bGenWoodActionPerformed
    
    private void bRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunActionPerformed
        if(inFile==null){
            JOptionPane.showMessageDialog(this, "Please choose a file for input", "No input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(outFile==null){
            JOptionPane.showMessageDialog(this, "Please choose a file for output", "No output", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WoodChecker check=new WoodChecker(inFile);
        if(!check.isWood()) {
            JOptionPane.showMessageDialog(this, "Not a Wood-File!", "Wrong file!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        view.compute(check,helpers,MBSaved,(lMode.getSelectedIndex()==0)?'e':'p',inFile,outFile);
    }//GEN-LAST:event_bRunActionPerformed

    private void bShowInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowInActionPerformed
        if(inFile==null) {
            JOptionPane.showMessageDialog(this, "Please select a file!", "No selection", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        WoodChecker check=new WoodChecker(inFile);
        if(!check.isWood()) {
            JOptionPane.showMessageDialog(this, "Not a Wood-File!", "Wrong file!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        view.show(inFile,outFile);
    }//GEN-LAST:event_bShowInActionPerformed

    private void mViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mViewerActionPerformed
       view.setVisible(true);
    }//GEN-LAST:event_mViewerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dAbout.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
        dAbout.setVisible(true);
    }//GEN-LAST:event_mAboutActionPerformed

    private void bTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTestActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Please save all data befor start!\nAll unsaved data will be lost!\nContinue?", "Crashtest!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        switch (result) {
            case JOptionPane.YES_OPTION:
                break;
            case JOptionPane.NO_OPTION:
                return;
            case JOptionPane.CLOSED_OPTION:
                return;
        }
        view.dispose();
        view=null;
        gen.dispose();
        gen=null;
        System.gc();
        Thread worker;
        status.setText("Initialize test"); 
        test=new Crashtest(status);
        test.prepare();
        worker = new Thread(new Runnable() {
            public void run() {
                test.start();
                processing.setVisible(false);
                test=null;
                initFrames();
            }
        });
        processing.setVisible(true);
        worker.start();
    }//GEN-LAST:event_bTestActionPerformed
        
    private void tHCountActionPerformed(FocusEvent evt) {                                        
        if(tHCount.getText().equals("")){
            tHCount.setText(helpers+"");
            return;
        }
        helpers=Integer.parseInt(tHCount.getText());
    }   
    
    private void tMBSavedActionPerformed(FocusEvent evt) {                                         
        if(tMBSaved.getText().equals("")){
            tMBSaved.setText(MBSaved+"");
            return;
        }
        MBSaved=Integer.parseInt(tMBSaved.getText());
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private class Verifier extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            int tmp;
            JTextField text = (JTextField)input;
            String value = text.getText().trim();
            try {
                tmp=Integer.parseInt(value);
                switch(text.getName()){
                    case "tHCount": if(tmp<0) throw new NumberFormatException();
                        helpers=tmp; break;
                    case "tMBSaved": if(tmp<0||tmp>100) throw new NumberFormatException();
                        MBSaved=tmp; break;
                    default:
                }
            } catch (NumberFormatException e) {
                switch(input.getName()){
                    case "tHCount": text.setText(helpers+""); break;
                    case "tMBSaved": text.setText(MBSaved+""); break;
                    default:
                }
               return false;
            }
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGenWood;
    private javax.swing.JButton bOpenIn;
    private javax.swing.JButton bOpenOut;
    private javax.swing.JButton bRun;
    private javax.swing.JButton bShowIn;
    private javax.swing.JMenuItem bTest;
    private javax.swing.JProgressBar bar;
    private javax.swing.JDialog dAbout;
    private javax.swing.JDialog dReplace;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lMode;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem mViewer;
    private javax.swing.JDialog processing;
    private javax.swing.JLabel status;
    private javax.swing.JButton stopTest;
    private javax.swing.JFormattedTextField tHCount;
    private javax.swing.JLabel tInput;
    private javax.swing.JFormattedTextField tMBSaved;
    private javax.swing.JLabel tOutput;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
